MACHINE = "nanopc-t6-lts"

# DISTRO_FEATURES:append = " opengl"
INHERIT += "extrausers"
EXTRA_USERS_PARAMS += "usermod -p '\$6\$gxNS0Q7nELte5Jk4\$t0XjxcHOCY6dt.zFXnenTAy8hnIZiSXXYSPGQjnkFASWXF8GRUqnf/NDBUTbhtc.cEuC0JFf4PdzEBarSODUK1' root;"